# Site
name: 'KangBlog'
description: 'KangBlog is a place I can share my view in Machine Learning, my experiments and thoughs in Kaggle competitions.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'khangdltuit@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Tuong-Khang:
      name:           Tuong-Khang
      site:           tuong-khang.github.io
      avatar:         /assets/images/avt.png
      bio:            "Hi, I am Khang, the author of KhangBlog, its blog is here I share my view in Machine Learning, experiments in Kaggle competitions. I hope you like it!"
      email:          khangdltuit@gmail.com
      twitter:        https://twitter.com/tuongkhangg

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Tuong-Khang
      avatar: /assets/images/avt.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]